In [ ]:
# 10.27 일 수업 대체 10장  numpy


In [4]:
import numpy as np
a=np.array([0,1,2,3])        #list 로 사용가능
print(a)

print(np.arange(10))         # numpy는 range를 arange로 사용

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
L=range(1000)
%timeit [i**2 for i in L]

164 µs ± 2.14 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
a= np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [11]:
a.ndim            # .ndim은 몇 차원인지 알려줌

1

In [12]:
a.shape          # shape는 (행,렬)을 표현 몇차원의 몇개인지 표현

(4,)

In [16]:
len(a)          #len은 차원 크리

4

In [28]:
b= np.array([[0,1,2],[3,4,5]])          #b는 2행 3열을 가진다.
b.ndim

2

In [22]:
b.shape             #axis=0 은 행 , axis=1은 열   seires=열

(2, 3)

In [24]:
len(b)

2

In [25]:
c=np.array([[0,1],[2,3],[4,5],[6,7]])
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
c.ndim

2

In [27]:
c.shape

(4, 2)

In [31]:
#using arange function
a=np.arange(10) #0,1,2....,n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b=np.arange(1,10,2) #start, end, step
b

array([1, 3, 5, 7, 9])

In [33]:
#using linspace
a=np.linspace(0,1,6)   #start, end ,numbers of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [34]:
#using ones 
a=np.ones((3,3))     # 모든 원소가 1로 구성되어
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
#using zeros
b=np.zeros((3,3))    #모든 원소가 0
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# using eye
c=np.eye(3)         #대각원소에 대해서 사용된다.
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
d= np.eye(3,2) # 3은 행, 2는 열
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [41]:
a=np.diag([1,5,3,4])
a

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [42]:
np.diag(a)

array([1, 5, 3, 4])

In [43]:
#numpy에는 random이 들어있어서 굳이 안불러도 사용 가능하다. 0과 1 사이의 랜덤값
a=np.random.rand(4)
a

array([0.35840493, 0.31358652, 0.15619102, 0.47858968])

In [45]:
a= np.random.randn(4)    #randn는 표준정규분포
a

array([-0.70478701, -1.06394009,  1.77912016, -1.42737312])

In [48]:
#using dtypeg
a= np.arange(10)
a.dtype                     

dtype('int32')

In [49]:
a=np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [54]:
d= np.array([1+2j,2+4j])          #복소수도 가능
print(d.dtype)

complex128


In [55]:
b=np.array([True,False])            #boolean도 가능
print(b.dtype)

bool


In [56]:
s=np.array(['Ram','Robert','Rahim'])
s.dtype

dtype('<U6')

In [57]:
a=np.arange(10)
print(a[5])

5


In [58]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [62]:
print(a[2,2])      

3


In [63]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [64]:
###########slicing ################

In [65]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a[1:8:2]  #[start index : endindex : step ]

array([1, 3, 5, 7])

In [69]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [71]:
b=np.arange(5)
a=b[::-1]               #[::-1] 은 역순을 뜻한다.
a  

array([4, 3, 2, 1, 0])

In [73]:
#####일부분을 택했을때 어딘가 할당되는게 아니라 기존의 메모리를 사용한다.
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [75]:
#np. shares_memory(a,b)   a와 b가 메모리를 공유하고 있는지 확인하는 함수 : True or False
np.shares_memory(a,b)

True

In [76]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [79]:
a                        # 둘이 메모리를 공유하고 있기때문에 0번째 인덱스가  10으로 바뀌었다.

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [80]:
a=np.arange(10)
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [81]:
np.shares_memory(a,c)

False

In [82]:
c[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a=np.random.randint(0,20,15)          # (start, end ,count)   start 와 end 사이의 15개를 뽑아라
a

array([ 2,  6,  6,  8, 10, 10,  8, 19, 18,  1, 13, 13,  5,  8, 13])

In [84]:
mask=(a%2==0)
mask                          #mask는 걸러지는것으로 True of False로 표현된다. 즉, 여기선 짝수인 부분만 True라고 표현될것이다.

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True, False])

In [85]:
extract_from_a=a[mask]
extract_from_a                #짝수인것만 출력

array([ 2,  6,  6,  8, 10, 10,  8, 18,  8])

In [86]:
mask=(a%3==0)
a[mask]=-1
a               #마스크에서 3으로 나누었을때 나머지값이 0인값이 -1로 지정하고 출력한것

array([ 2, -1, -1,  8, 10, 10,  8, 19, -1,  1, 13, 13,  5,  8, 13])

In [87]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [89]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [90]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [91]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [92]:
b=np.ones(4)+1           #모든 원소가 1인 4개의 행에 1씩 더한다
a-b

array([-1.,  0.,  1.,  2.])

In [93]:
a*b

array([2., 4., 6., 8.])

In [94]:
c=np.diag([1,2,3,4])

print(c*c)
print("********************")
print(c.dot(c))             #dot(x) x**2 괄호안의 변수를 제곱하는것

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [97]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [98]:
a>b

array([False, False,  True, False])

In [101]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

np.array_equal(a,c)

True

In [102]:
np.array_equal(a,b)

False

In [103]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)

np.logical_or(a,b)               #True=1 False=0 or이기때문에 한쪽이라도 1의 값을 가지면 True , 나머지는 False

array([ True,  True,  True, False])

In [104]:
np.logical_and(a,b)

array([ True, False, False, False])

In [105]:
a=np.arange(40)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539])

In [106]:
np.log(a)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11804\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165])

In [107]:
np.exp(a)    #e^a로 변환

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16])

In [108]:
a=np.arange(4)
a+np,array([1,2])            # 항상 사칙연상은 shape가 동일해야 연산이 가능하다

TypeError: unsupported operand type(s) for +: 'int' and 'module'

In [109]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [113]:
x=np.array([[1,2],[3,4]])
x.sum(axis=0)                #'열'끼리 합

array([4, 6])

In [114]:
x.sum(axis=1)              #  '행' 끼리 합

array([3, 7])

In [115]:
x.max()

4

In [117]:
x.argmin()                # index값을 변환 그 중 min 여기선 제일 작은 값이 있는 인덱스 0

0

In [118]:
x.argmax()                # index값을 변환 그 중 max 여기선 제일 큰 값이 있는 인덱스 3

3

In [119]:
np.all([True,True,False])           # and 와 같은 개념으로 모두 True여야만 True이다

False

In [120]:
np.any([True,True,False])           # or 와 같은 개념으로 아무거나 True이면 True이다

True

In [121]:
a=np.zeros((50,50))            # 50행 50영
np.any(a!=0)                   # 하나라도 0이 아닌것이 있냐

False

In [122]:
np.all(a==a)

True

In [124]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).all()

True

In [127]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [128]:
y.mean()

3.0

In [129]:
np.median(x)      #median은 중위수 

1.5

In [130]:
np.median(y, axis=-1)          #axis=-1 은 마지막 축을 위미하는데

array([2., 5.])

In [131]:
x.std()                  # std는 표준편차|

0.82915619758885